language: ruby
rvm:
  # - 2.2.7
  # - 2.3.4
  - 2.4.1
services:
  - postgresql
before_script:
  - psql -U postgres -c "CREATE DATABASE pact_broker;"
  # - psql -U postgres -c "GRANT ALL PRIVILEGES ON DATABASE pact_broker TO pact_broker;"
script:
  - bundle exec rake
env:
  - DATABASE_ADAPTER=default
  - DATABASE_ADAPTER=postgres
