language: ruby
rvm:
  - 2.4.1
services:
  - mysql
addons:
  postgresql: "9.5"
env:
  matrix:
    - DATABASE_ADAPTER=mysql RUBYOPT="-W0"
before_script:
  - cp config/database.travis.yml config/database.yml
  - mysql -e 'CREATE DATABASE pact_broker;'
  - mysql -e "GRANT ALL ON pact_broker.* TO 'travis'@'%';"
script:
  - bundle exec rake spec:broken

