language: ruby
rvm:
  - 2.4.1
  - 2.5
services:
  - postgresql
  - mysql
addons:
  postgresql: "9.5"
env:
  global:
    - CC_TEST_REPORTER_ID=dc2c30b67c9e2a5309e1aef699c30fdab55ba4f0e4f1beac029ba93e293835db
    - GIT_COMMITTED_AT=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then git log -1 --pretty=format:%ct; else git log -1 --skip 1 --pretty=format:%ct; fi)
    - INSTALL_MYSQL=true
  matrix:
    - DATABASE_ADAPTER=default RUBYOPT="-W0"
    - DATABASE_ADAPTER=postgres RUBYOPT="-W0"
    - DATABASE_ADAPTER=mysql RUBYOPT="-W0"
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -U postgres -c "CREATE DATABASE pact_broker;"
  - mysql -e 'CREATE DATABASE pact_broker;'
  - mysql -e "GRANT ALL ON pact_broker.* TO 'travis'@'%';"
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
script:
  - bundle exec rake
  - if [ "$DATABASE_ADAPTER" == "postgres" ]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT || true; fi
  # - if [ ! -z "$(ruby --version | grep '2\.4\.')" ]; then ./script/db-spec.sh; fi
jobs:
  include:
    - stage: gem release
      rvm: 2.5
      script: echo "Deploying to rubygems.org ..."
      deploy:
        provider: rubygems
        api_key:
          secure: AzTHDbKRr1ZO4E2mRyvU054Tx8c2cZbKkoDBZjSAQ2CY3E7oH137NTAIGd4BthH/E9mbEXtGpZIDfWPbaOcUJQ5Bz24CWTKmGyic6FrPhJnOW5CKVSLGCDPzpmqHULv/GTN16YN0Dh1HLeGYZzlHlxT0+4AVvbvBAleHrAFeJs8=
        gem: pact_broker
        on:
          tags: true
          repo: pact-foundation/pact_broker
