language: ruby
rvm:
  # - 2.2.7
  # - 2.3.4
  - 2.4.1
services:
  - postgresql
  - mysql
addons:
  postgresql: "9.5"
env:
  global:
    - CC_TEST_REPORTER_ID=dc2c30b67c9e2a5309e1aef699c30fdab55ba4f0e4f1beac029ba93e293835db
    - GIT_COMMITTED_AT=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then git log -1 --pretty=format:%ct; else git log -1 --skip 1 --pretty=format:%ct; fi)
  matrix:
    - DATABASE_ADAPTER=default RUBYOPT="-W0"
    - DATABASE_ADAPTER=postgres RUBYOPT="-W0"
    - DATABASE_ADAPTER=mysql RUBYOPT="-W0"
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -U postgres -c "CREATE DATABASE pact_broker;"
  - mysql -e 'CREATE DATABASE pact_broker;'
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
script:
  - bundle exec rake
  - if [ "$DATABASE_ADAPTER" == "postgres" ]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT || true; fi
  - bundle exec bundle-audit update && bundle exec bundle-audit
