version: "3"

services:
  mysql:
    image: mysql:9.5.0@sha256:57c892ddeb17e6c7dddf219914db017b2cf3e2797806a75424444b83622cc8ef
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: pact_broker
      MYSQL_DATABASE: pact_broker
      MYSQL_USER: pact_broker
      MYSQL_PASSWORD: pact_broker
    ports:
      - "3306:3306"

  tests:
    build: .
    depends_on:
      - mysql
    environment:
      DATABASE_ADAPTER: docker_compose_mysql
      PACT_BROKER_HIDE_PACTFLOW_MESSAGES: 'true'
    volumes:
      - ./lib:/home/lib
      - ./spec:/home/spec
      - ./db:/home/db
      - ./config.ru:/home/config.ru
      - ./tasks:/home/tasks
      - ./Rakefile:/home/Rakefile
      - ./config:/home/config
      - ./.rspec:/home/.rspec
      - ./.rubocop:/home/.rubocop
      - ./.gitignore:/home/.gitignore
      - ./public:/home/public
      - ./script/docker-container/test.sh:/usr/local/bin/test
      - ./docs:/home/docs
      - ./pact_broker_oas.yaml:/home/pact_broker_oas.yaml
    entrypoint: dockerize
    command: --wait tcp://mysql:3306 -timeout 60s test
