name: Test

on: push

jobs:
  sqlite:
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        ruby_version: ["2.7"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
      - run: "bundle install"
      - run: "bundle exec rake"
  postgres:
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false
      matrix:
        ruby_version: ["2.5", "2.7", "3.0"]
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
      - run: "gem install bundler && bundle install"
        env:
          INSTALL_PG: "true"
      - run: "bundle exec rake"
        env:
          DATABASE_ADAPTER: github_actions_postgres
          INSTALL_PG: "true"
  mysql:
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        ruby_version: ["2.7"]
    steps:
      - uses: actions/checkout@v2
      - run: script/test/run-rake-on-docker-compose-mysql.sh
